package lintgate

import (
	"errors"
	"os"
	"path/filepath"
	"strings"
	"testing"
)

// fakeRepo is a directory standing in for a checkout, with git answered by a
// fake that only knows where the hooks directory is.
type fakeRepo struct {
	t     *testing.T
	root  string
	hooks string
}

func newRepo(t *testing.T) *fakeRepo {
	root := t.TempDir()
	return &fakeRepo{t: t, root: root, hooks: filepath.Join(root, ".git", "hooks")}
}

func (r *fakeRepo) write(rel, body string) string {
	r.t.Helper()
	p := rel
	if !filepath.IsAbs(p) {
		p = filepath.Join(r.root, rel)
	}
	if err := os.MkdirAll(filepath.Dir(p), 0o755); err != nil {
		r.t.Fatal(err)
	}
	if err := os.WriteFile(p, []byte(body), 0o755); err != nil {
		r.t.Fatal(err)
	}
	return p
}

func (r *fakeRepo) git(dir string, args ...string) (string, error) {
	if dir != r.root {
		return "", errors.New("unexpected dir " + dir)
	}
	if strings.Join(args, " ") == "rev-parse --path-format=absolute --git-path hooks" {
		return r.hooks, nil
	}
	return "", errors.New("unexpected git " + strings.Join(args, " "))
}

func (r *fakeRepo) detect() Gate { return Detect(r.root, "saddle/integration", r.git) }

const makefile = "check: lint test\n\nlint:\n\tgolangci-lint run\n\nfix:\n\tgofmt -w .\n"

func TestDetectNone(t *testing.T) {
	r := newRepo(t)
	r.write("go.mod", "module x\n")
	if g := r.detect(); g.Cmd != "" || g.Kind != "" {
		t.Fatalf("no gate: %+v", g)
	}
}

func TestDetectInstalledHookRunningMake(t *testing.T) {
	r := newRepo(t)
	r.write("Makefile", makefile)
	r.write(".git/hooks/pre-commit", "#!/bin/sh\nset -e\nmake check\n")
	g := r.detect()
	if g.Kind != KindHook || g.Cmd != "make check" || g.Fix != "make fix" {
		t.Fatalf("%+v", g)
	}
	if g.Hook != filepath.Join(r.hooks, "pre-commit") {
		t.Fatalf("hook %q", g.Hook)
	}
}

func TestDetectInstalledHookSymlink(t *testing.T) {
	r := newRepo(t)
	// quark's layout: git/hooks/pre-commit is tracked, `make setup/hooks`
	// symlinks it into .git/hooks.
	src := r.write("git/hooks/pre-commit", "#!/usr/bin/env bash\nexec make -s check\n")
	if err := os.MkdirAll(r.hooks, 0o755); err != nil {
		t.Fatal(err)
	}
	if err := os.Symlink(src, filepath.Join(r.hooks, "pre-commit")); err != nil {
		t.Fatal(err)
	}
	g := r.detect()
	if g.Kind != KindHook || g.Cmd != "make check" || g.Shipped != "" {
		t.Fatalf("%+v", g)
	}
}

func TestDetectHookWithoutMakeRunsTheHook(t *testing.T) {
	r := newRepo(t)
	p := r.write(".git/hooks/pre-commit", "#!/bin/sh\ngofmt -l . | grep . && exit 1\nexit 0\n")
	g := r.detect()
	if g.Kind != KindHook || g.Cmd != "'"+p+"'" {
		t.Fatalf("%+v", g)
	}
}

func TestDetectCoreHooksPath(t *testing.T) {
	r := newRepo(t)
	// core.hooksPath moves the hooks directory; git rev-parse reports it.
	r.hooks = filepath.Join(r.root, ".githooks")
	r.write(".githooks/pre-commit", "#!/bin/sh\nmake lint\n")
	r.write("Makefile", makefile)
	g := r.detect()
	if g.Kind != KindHook || g.Cmd != "make lint" || g.Hook != filepath.Join(r.hooks, "pre-commit") {
		t.Fatalf("%+v", g)
	}
}

func TestDetectPreCommitFramework(t *testing.T) {
	r := newRepo(t)
	r.write(".pre-commit-config.yaml", "repos: []\n")
	g := r.detect()
	if g.Kind != KindPreCommit || g.Cmd != "pre-commit run --from-ref saddle/integration --to-ref HEAD" || g.Hook != "" {
		t.Fatalf("%+v", g)
	}
	// Installed, its hook says so; the command is the same.
	r.write(".git/hooks/pre-commit", "#!/usr/bin/env bash\n# File generated by pre-commit: https://pre-commit.com\nexec pre-commit hook-impl\n")
	if g := r.detect(); g.Kind != KindPreCommit || g.Hook == "" || !strings.HasPrefix(g.Cmd, "pre-commit run") {
		t.Fatalf("installed: %+v", g)
	}
}

func TestDetectLefthook(t *testing.T) {
	r := newRepo(t)
	r.write("lefthook.yml", "pre-commit:\n  commands: {}\n")
	if g := r.detect(); g.Kind != KindLefthook || g.Cmd != "lefthook run pre-commit --all-files" {
		t.Fatalf("%+v", g)
	}
}

func TestDetectHusky(t *testing.T) {
	r := newRepo(t)
	r.write(".husky/pre-commit", "npx lint-staged\n")
	if g := r.detect(); g.Kind != KindHusky || g.Cmd != "sh .husky/pre-commit" {
		t.Fatalf("%+v", g)
	}
}

func TestDetectShippedButNotInstalledHook(t *testing.T) {
	r := newRepo(t)
	r.write("Makefile", "check:\n\tgo test ./...\nsetup/hooks:\n\tln -sf ../../git/hooks/pre-commit .git/hooks/pre-commit\n")
	r.write("git/hooks/pre-commit", "#!/bin/sh\nmake check\n")
	g := r.detect()
	if g.Kind != KindHook || g.Cmd != "make check" || g.Hook != "" || g.Shipped != "git/hooks/pre-commit" {
		t.Fatalf("%+v", g)
	}
}

func TestDetectMakefileTargets(t *testing.T) {
	r := newRepo(t)
	r.write("Makefile", "lint:\n\tgolangci-lint run\nlint/fix:\n\tgolangci-lint run --fix\n")
	if g := r.detect(); g.Kind != KindMake || g.Cmd != "make lint" || g.Fix != "make lint/fix" {
		t.Fatalf("%+v", g)
	}
	r.write("Makefile", makefile)
	if g := r.detect(); g.Cmd != "make check" || g.Fix != "make fix" {
		t.Fatalf("check wins over lint: %+v", g)
	}
	// A variable named check is not a target.
	r.write("Makefile", "check := yes\n")
	if g := r.detect(); g.Cmd != "" {
		t.Fatalf("variable: %+v", g)
	}
}

func TestDetectSkipsSaddleChainedHook(t *testing.T) {
	r := newRepo(t)
	// A saddle wrapper chained the repo's hook to pre-commit.pre-saddle.
	r.write(".git/hooks/pre-commit", "#!/bin/sh\n# saddle refguard: chained\n")
	r.write(".git/hooks/pre-commit"+ChainSuffix, "#!/bin/sh\nmake check\n")
	if g := r.detect(); g.Kind != KindHook || g.Cmd != "make check" {
		t.Fatalf("%+v", g)
	}
}

func TestDetectNoGitFallsBackToFiles(t *testing.T) {
	r := newRepo(t)
	r.write("Makefile", makefile)
	g := Detect(r.root, "main", func(string, ...string) (string, error) { return "", errors.New("not a repo") })
	if g.Kind != KindMake || g.Cmd != "make check" {
		t.Fatalf("%+v", g)
	}
}
