// Package lintgate finds a repo's own pre-commit/lint gate: the check its
// developers' commits must pass before anything is pushed. Saddle runs the
// same check before an agent may call done and before the merge train lands
// a branch, so saddle-built work never skips it (#212).
//
// Detect looks, in order, at the installed pre-commit hook (the hooks
// directory git reports, which honors core.hooksPath), the pre-commit
// framework, lefthook, husky, a hook script the repo ships but hasn't
// installed, and Makefile check/lint targets. It reads files from the
// checkout and asks git only through the injected Git.
package lintgate

import (
	"os"
	"path/filepath"
	"regexp"
	"strings"
)

// Kinds of gate.
const (
	KindHook      = "pre-commit hook"
	KindPreCommit = "pre-commit"
	KindLefthook  = "lefthook"
	KindHusky     = "husky"
	KindMake      = "Makefile"
)

// ChainSuffix names where saddle's hook installer moves a repo hook it
// chains: <hooks>/<name><ChainSuffix>.
const ChainSuffix = ".pre-saddle"

// Git runs git in dir and returns its trimmed stdout.
type Git func(dir string, args ...string) (string, error)

// Gate is a repo's detected gate. Cmd is empty when there is none.
type Gate struct {
	Kind string
	// Source is the file the gate was found in.
	Source string
	// Cmd runs the gate from the top of a worktree; non-zero means red.
	Cmd string
	// Fix is the repo's fixer (make fix and the like), if it has one.
	Fix string
	// Hook is the installed pre-commit hook, "" when none is installed.
	Hook string
	// Shipped is a repo-relative hook script the repo ships but that isn't
	// installed, e.g. git/hooks/pre-commit waiting on `make setup/hooks`.
	Shipped string
}

// shippedDirs are where repos keep hook scripts for developers to install.
var shippedDirs = []string{"git/hooks", ".githooks", "githooks", ".hooks", "hooks", "scripts/git-hooks", "scripts/hooks"}

// Detect returns the gate of the checkout at root. base is the branch work is
// compared against, for gates that check only changed files.
func Detect(root, base string, git Git) Gate {
	g := detect(root, base, git)
	if g.Fix == "" {
		g.Fix = makeFix(root)
	}
	return g
}

func detect(root, base string, git Git) Gate {
	if hooks, err := git(root, "rev-parse", "--path-format=absolute", "--git-path", "hooks"); err == nil && hooks != "" {
		path := filepath.Join(hooks, "pre-commit")
		script := path
		if _, err := os.Stat(path + ChainSuffix); err == nil {
			script = path + ChainSuffix
		}
		if b, err := os.ReadFile(script); err == nil {
			g := fromScript(root, base, string(b), script)
			g.Source, g.Hook = script, path
			return g
		}
	}
	if p, ok := first(root, ".pre-commit-config.yaml", ".pre-commit-config.yml"); ok {
		return Gate{Kind: KindPreCommit, Source: p, Cmd: preCommitCmd(base)}
	}
	if p, ok := first(root, "lefthook.yml", "lefthook.yaml", ".lefthook.yml", ".lefthook.yaml"); ok {
		return Gate{Kind: KindLefthook, Source: p, Cmd: lefthookCmd}
	}
	if p, ok := first(root, ".husky/pre-commit"); ok {
		return Gate{Kind: KindHusky, Source: p, Cmd: "sh .husky/pre-commit"}
	}
	for _, d := range shippedDirs {
		rel := d + "/pre-commit"
		b, err := os.ReadFile(filepath.Join(root, rel))
		if err != nil {
			continue
		}
		g := fromScript(root, base, string(b), filepath.Join(root, rel))
		g.Source, g.Shipped = rel, rel
		return g
	}
	for _, t := range []string{"check", "lint"} {
		if hasTarget(root, t) {
			return Gate{Kind: KindMake, Source: "Makefile", Cmd: "make " + t}
		}
	}
	return Gate{}
}

const lefthookCmd = "lefthook run pre-commit --all-files"

func preCommitCmd(base string) string {
	return "pre-commit run --from-ref " + base + " --to-ref HEAD"
}

var makeRe = regexp.MustCompile(`\bmake((?:\s+-[A-Za-z]+)*)\s+([A-Za-z0-9_][A-Za-z0-9_/.-]*)`)

// fromScript classifies a pre-commit hook script found at path.
func fromScript(root, base, script, path string) Gate {
	switch {
	case strings.Contains(script, "pre-commit.com") || strings.Contains(script, "File generated by pre-commit"):
		return Gate{Kind: KindPreCommit, Cmd: preCommitCmd(base)}
	case strings.Contains(script, "lefthook"):
		return Gate{Kind: KindLefthook, Cmd: lefthookCmd}
	case strings.Contains(script, "husky"):
		if _, ok := first(root, ".husky/pre-commit"); ok {
			return Gate{Kind: KindHusky, Cmd: "sh .husky/pre-commit"}
		}
	}
	var code []string
	for _, line := range strings.Split(script, "\n") {
		if t := strings.TrimSpace(line); t != "" && !strings.HasPrefix(t, "#") {
			code = append(code, t)
		}
	}
	if m := makeRe.FindStringSubmatch(strings.Join(code, "\n")); m != nil {
		return Gate{Kind: KindHook, Cmd: "make " + m[2]}
	}
	return Gate{Kind: KindHook, Cmd: shellQuote(path)}
}

func first(root string, names ...string) (string, bool) {
	for _, n := range names {
		if _, err := os.Stat(filepath.Join(root, n)); err == nil {
			return n, true
		}
	}
	return "", false
}

// makeFix is the Makefile's fixer target, if any.
func makeFix(root string) string {
	for _, t := range []string{"fix", "lint/fix", "lint-fix", "fmt", "format"} {
		if hasTarget(root, t) {
			return "make " + t
		}
	}
	return ""
}

// hasTarget reports whether the Makefile at root defines target. A line
// `target:` counts; `target := value` is a variable.
func hasTarget(root, target string) bool {
	b, err := os.ReadFile(filepath.Join(root, "Makefile"))
	if err != nil {
		return false
	}
	re := regexp.MustCompile(`(?m)^` + regexp.QuoteMeta(target) + `[ \t]*:([^=]|$)`)
	return re.Match(b)
}

func shellQuote(s string) string {
	return "'" + strings.ReplaceAll(s, "'", `'\''`) + "'"
}
