// Package agent launches coding agents. Claude Code is the only adapter in M0.
package agent

import (
	"encoding/json"
	"fmt"
	"os"
	"path/filepath"
	"strings"
)

// Launch describes one agent session to start in a tmux window.
type Launch struct {
	Root     string // main checkout
	Bin      string // absolute path to the saddle binary
	Task     string
	Title    string
	Dir      string // working directory (the task worktree, or root for the orchestrator)
	Model    string
	Mode     string // claude --permission-mode
	Cmd      string // claude executable
	Brief    string // appended to the system prompt
	Prompt   string // first user message
	RunDir   string // where launch files are written
	ExtraEnv map[string]string
}

// Write creates the launch files and returns the shell command for the window.
func (l Launch) Write() (string, error) {
	if err := os.MkdirAll(l.RunDir, 0o755); err != nil {
		return "", err
	}
	hook := func() []map[string]any {
		return []map[string]any{{"type": "command", "command": shellQuote(l.Bin) + " hook", "timeout": 10}}
	}
	settings := map[string]any{
		"hooks": map[string]any{
			"PreToolUse":       []any{map[string]any{"matcher": "Edit|Write|MultiEdit|NotebookEdit", "hooks": hook()}},
			"PostToolUse":      []any{map[string]any{"matcher": "*", "hooks": hook()}},
			"UserPromptSubmit": []any{map[string]any{"hooks": hook()}},
			"Stop":             []any{map[string]any{"hooks": hook()}},
			"Notification":     []any{map[string]any{"hooks": hook()}},
			"SessionStart":     []any{map[string]any{"hooks": hook()}},
		},
		"permissions": map[string]any{
			// saddle's PreToolUse hook is the write guard, so edits need no prompt.
			"allow": []string{"mcp__saddle", "Edit", "Write", "MultiEdit", "NotebookEdit",
				"Bash(saddle sync:*)", "Bash(saddle status:*)", "Bash(git add:*)", "Bash(git commit:*)",
				"Bash(git status:*)", "Bash(git diff:*)", "Bash(git log:*)", "Bash(git rebase --continue:*)"},
		},
	}
	env := map[string]string{"SADDLE_ROOT": l.Root, "SADDLE_TASK": l.Task}
	for k, v := range l.ExtraEnv {
		env[k] = v
	}
	mcp := map[string]any{"mcpServers": map[string]any{
		"saddle": map[string]any{"type": "stdio", "command": l.Bin, "args": []string{"mcp"}, "env": env},
	}}
	files := map[string]string{
		"brief.md":  l.Brief,
		"prompt.md": l.Prompt,
	}
	for name, v := range map[string]any{"settings.json": settings, "mcp.json": mcp} {
		b, err := json.MarshalIndent(v, "", "  ")
		if err != nil {
			return "", err
		}
		files[name] = string(b)
	}
	for name, body := range files {
		if err := os.WriteFile(filepath.Join(l.RunDir, name), []byte(body), 0o644); err != nil {
			return "", err
		}
	}

	var sh strings.Builder
	sh.WriteString("#!/usr/bin/env bash\n# Generated by saddle. Re-run to restart this agent.\n")
	for _, k := range []string{"SADDLE_ROOT", "SADDLE_TASK"} {
		fmt.Fprintf(&sh, "export %s=%s\n", k, shellQuote(env[k]))
	}
	fmt.Fprintf(&sh, "export PATH=%s:\"$PATH\"\n", shellQuote(filepath.Dir(l.Bin)))
	fmt.Fprintf(&sh, "cd %s || exit 1\n", shellQuote(l.Dir))
	fmt.Fprintf(&sh, "run=%s\n", shellQuote(l.RunDir))
	args := []string{shellQuote(l.Cmd)}
	if l.Model != "" {
		args = append(args, "--model", shellQuote(l.Model))
	}
	if l.Mode != "" {
		args = append(args, "--permission-mode", shellQuote(l.Mode))
	}
	args = append(args,
		"--settings", `"$run/settings.json"`,
		"--mcp-config", `"$run/mcp.json"`,
		"-n", shellQuote("saddle "+l.Task+": "+l.Title),
		"--append-system-prompt", `"$(cat "$run/brief.md")"`,
	)
	if l.Prompt != "" {
		args = append(args, `"$(cat "$run/prompt.md")"`)
	}
	sh.WriteString(strings.Join(args, " ") + "\n")
	fmt.Fprintf(&sh, "%s exited %s >/dev/null 2>&1\n", shellQuote(l.Bin), shellQuote(l.Task))
	sh.WriteString("echo; echo \"[saddle] agent exited. Re-run: bash $run/launch.sh\"; exec \"${SHELL:-bash}\"\n")

	launch := filepath.Join(l.RunDir, "launch.sh")
	if err := os.WriteFile(launch, []byte(sh.String()), 0o755); err != nil {
		return "", err
	}
	return "bash " + shellQuote(launch), nil
}

func shellQuote(s string) string {
	return "'" + strings.ReplaceAll(s, "'", `'\''`) + "'"
}
