package agent

import (
	"encoding/json"
	"fmt"
	"os"
	"os/exec"
	"path/filepath"
	"strings"

	"github.com/brandonapol/saddle/internal/usage"
)

// grokSpec is the headless invocation saddle's grok-bridge replays once per
// user message. Interactive workers don't use it; they get launch.sh instead.
type grokSpec struct {
	Cmd    string   `json:"cmd"`
	Args   []string `json:"args"`
	Dir    string   `json:"dir"`
	Env    []string `json:"env"`
	Resume string   `json:"resume,omitempty"`
}

// grokHarnessMark is written into a run dir whose grok session has project
// hooks, so saddle treats claims as enforced rather than advisory.
const grokHarnessMark = "grok-harness"

// GrokHarnessOn reports whether runDir was launched as the grok harness.
func GrokHarnessOn(runDir string) bool {
	_, err := os.Stat(filepath.Join(runDir, grokHarnessMark))
	return err == nil
}

func (l Launch) writeGrok() (string, error) {
	if err := l.prepareGrok(); err != nil {
		return "", err
	}
	env := l.env()
	var sh strings.Builder
	sh.WriteString("#!/usr/bin/env bash\n# Generated by saddle. Re-run to restart this agent.\n")
	for _, k := range []string{"SADDLE_ROOT", "SADDLE_TASK"} {
		fmt.Fprintf(&sh, "export %s=%s\n", k, shellQuote(env[k]))
	}
	fmt.Fprintf(&sh, "export PATH=%s:\"$PATH\"\n", shellQuote(filepath.Dir(l.Bin)))
	fmt.Fprintf(&sh, "cd %s || exit 1\n", shellQuote(l.Dir))
	fmt.Fprintf(&sh, "run=%s\n", shellQuote(l.RunDir))
	args := append([]string{l.cmd()}, l.grokArgs(false)...)
	quoted := make([]string, len(args))
	for i, a := range args {
		quoted[i] = shellQuote(a)
	}
	fmt.Fprintf(&sh, "args=(%s)\n", strings.Join(quoted, " "))
	if l.Prompt != "" {
		sh.WriteString("args+=(-- \"$(cat \"$run/prompt.md\")\")\n")
	}
	sh.WriteString("\"${args[@]}\"\n")
	fmt.Fprintf(&sh, "status=$?\n%s exited %s >/dev/null 2>&1 || true\n", shellQuote(l.Bin), shellQuote(l.Task))
	sh.WriteString("echo; echo \"[saddle] agent exited ($status). Re-run: bash $run/launch.sh\"; exec \"${SHELL:-bash}\"\n")

	launch := filepath.Join(l.RunDir, "launch.sh")
	if err := os.WriteFile(launch, []byte(sh.String()), 0o755); err != nil {
		return "", err
	}
	return "bash " + shellQuote(launch), nil
}

func (l Launch) headlessGrok(resume string) (*exec.Cmd, error) {
	if err := l.prepareGrok(); err != nil {
		return nil, err
	}
	spec := grokSpec{
		Cmd: l.cmd(), Args: l.grokArgs(true), Dir: l.Dir, Resume: resume,
		Env: envList(l.env()),
	}
	b, err := json.MarshalIndent(spec, "", "  ")
	if err != nil {
		return nil, err
	}
	if err := os.WriteFile(filepath.Join(l.RunDir, "grok.json"), b, 0o644); err != nil {
		return nil, err
	}
	cmd := exec.Command(l.Bin, "grok-bridge", l.RunDir)
	cmd.Dir = l.Dir
	cmd.Env = append(os.Environ(), spec.Env...)
	cmd.Env = append(cmd.Env, "PATH="+filepath.Dir(l.Bin)+string(os.PathListSeparator)+os.Getenv("PATH"))
	return cmd, nil
}

func (l Launch) cmd() string {
	if l.Cmd != "" {
		return l.Cmd
	}
	return "grok"
}

func envList(env map[string]string) []string {
	out := make([]string, 0, len(env))
	for _, k := range []string{"SADDLE_ROOT", "SADDLE_TASK"} {
		if v, ok := env[k]; ok {
			out = append(out, k+"="+v)
		}
	}
	for k, v := range env {
		if k == "SADDLE_ROOT" || k == "SADDLE_TASK" {
			continue
		}
		out = append(out, k+"="+v)
	}
	return out
}

// grokArgs are the flags shared by the interactive worker and each headless
// orchestrator turn. The prompt itself is added by the caller.
func (l Launch) grokArgs(headless bool) []string {
	args := []string{"--no-auto-update", "--trust"}
	if !headless {
		// Alt-screen hides the transcript from tmux capture-pane, which is how
		// saddle peeks a worker.
		args = append(args, "--no-alt-screen")
	}
	mode := l.Mode
	if mode == "" {
		mode = "bypassPermissions"
	}
	args = append(args, "--permission-mode", mode)
	if l.Model != "" {
		args = append(args, "--model", l.Model)
	}
	if l.Brief != "" {
		args = append(args, "--rules", l.Brief)
	}
	tools, rules, noSub := splitGrokDeny(l.Deny)
	if noSub {
		args = append(args, "--no-subagents")
	}
	if len(tools) > 0 {
		args = append(args, "--disallowed-tools", strings.Join(tools, ","))
	}
	for _, r := range rules {
		args = append(args, "--deny", r)
	}
	args = append(args, l.Args...) // [adapters.grok] args
	if headless {
		// streaming-messages-json is the Claude stream-json wire format the
		// orchestrator already parses, including stream_event deltas.
		args = append(args, "--output-format", "streaming-messages-json", "--include-partial-messages")
	}
	return args
}

// splitGrokDeny turns Claude's deny list into grok flags. Bash(...) rules stay
// deny rules. Write tools also drop grok's own editors. Agent becomes
// --no-subagents. Scheduler tools Claude has and grok doesn't are dropped.
func splitGrokDeny(deny []string) (tools, rules []string, noSub bool) {
	seen := map[string]bool{}
	add := func(names ...string) {
		for _, n := range names {
			if n != "" && !seen[n] {
				tools = append(tools, n)
				seen[n] = true
			}
		}
	}
	write := false
	for _, d := range deny {
		if strings.Contains(d, "(") {
			rules = append(rules, d)
			continue
		}
		switch d {
		case "Agent":
			noSub = true
			add("spawn_subagent")
			continue
		case "ScheduleWakeup", "CronCreate":
			add("scheduler_create", "scheduler_delete", "scheduler_list")
			continue
		case "Monitor":
			add("monitor")
			continue
		case "Edit", "Write", "MultiEdit", "NotebookEdit":
			write = true
		}
		add(d)
	}
	if write {
		add("write", "write_file", "search_replace", "apply_patch")
	}
	return tools, rules, noSub
}

func (l Launch) prepareGrok() error {
	if err := l.record(usage.Grok); err != nil {
		return err
	}
	if err := os.WriteFile(filepath.Join(l.RunDir, grokHarnessMark), []byte("1\n"), 0o644); err != nil {
		return err
	}
	if err := os.WriteFile(filepath.Join(l.RunDir, "brief.md"), []byte(l.Brief), 0o644); err != nil {
		return err
	}
	if err := os.WriteFile(filepath.Join(l.RunDir, "prompt.md"), []byte(l.Prompt), 0o644); err != nil {
		return err
	}
	if l.Dir == "" {
		return nil
	}
	if err := l.writeGrokProject(); err != nil {
		return err
	}
	return nil
}

// writeGrokProject installs the per-directory hooks and MCP server grok reads
// from the worktree. They are gitexcluded so a worker does not commit them.
// --trust (passed at launch) is what lets grok run project hooks.
func (l Launch) writeGrokProject() error {
	hookDir := filepath.Join(l.Dir, ".grok", "hooks")
	if err := os.MkdirAll(hookDir, 0o755); err != nil {
		return err
	}
	cmd := shellQuote(l.Bin) + " hook"
	group := []any{map[string]any{"hooks": []any{map[string]any{"type": "command", "command": cmd, "timeout": 10}}}}
	hooks := map[string]any{}
	for _, ev := range []string{"SessionStart", "PreToolUse", "PostToolUse", "UserPromptSubmit", "Stop", "Notification"} {
		hooks[ev] = group
	}
	b, err := json.MarshalIndent(map[string]any{"hooks": hooks}, "", "  ")
	if err != nil {
		return err
	}
	if err := os.WriteFile(filepath.Join(hookDir, "saddle.json"), append(b, '\n'), 0o644); err != nil {
		return err
	}
	createdConfig, err := ensureGrokMCP(l.Dir, l.Bin, l.env())
	if err != nil {
		return err
	}
	patterns := []string{"/.grok/hooks/saddle.json"}
	if createdConfig {
		patterns = append(patterns, "/.grok/config.toml")
	}
	ensureGitExclude(l.Dir, patterns)
	return nil
}

// ensureGrokMCP appends the saddle stdio server when the project config does
// not already name it. created is true when this call created the file, so
// the caller can gitexclude it.
func ensureGrokMCP(dir, bin string, env map[string]string) (created bool, err error) {
	path := filepath.Join(dir, ".grok", "config.toml")
	body, err := os.ReadFile(path)
	if err != nil && !os.IsNotExist(err) {
		return false, err
	}
	if strings.Contains(string(body), "[mcp_servers.saddle]") {
		return false, nil
	}
	var b strings.Builder
	if len(body) > 0 && !strings.HasSuffix(string(body), "\n") {
		b.WriteByte('\n')
	}
	b.WriteString("\n# Added by saddle so this agent can call claim, spawn and done.\n")
	b.WriteString("[mcp_servers.saddle]\n")
	fmt.Fprintf(&b, "command = %s\n", tomlBasic(bin))
	b.WriteString("args = [\"mcp\"]\n\n")
	b.WriteString("[mcp_servers.saddle.env]\n")
	for _, k := range []string{"SADDLE_ROOT", "SADDLE_TASK"} {
		fmt.Fprintf(&b, "%s = %s\n", k, tomlBasic(env[k]))
	}
	if err := os.MkdirAll(filepath.Dir(path), 0o755); err != nil {
		return false, err
	}
	f, err := os.OpenFile(path, os.O_APPEND|os.O_CREATE|os.O_WRONLY, 0o644)
	if err != nil {
		return false, err
	}
	defer f.Close()
	_, err = f.WriteString(b.String())
	return len(body) == 0, err
}

func tomlBasic(s string) string {
	r := strings.NewReplacer(`\`, `\\`, `"`, `\"`, "\n", `\n`)
	return `"` + r.Replace(s) + `"`
}

func ensureGitExclude(dir string, patterns []string) {
	out, err := exec.Command("git", "-C", dir, "rev-parse", "--git-path", "info/exclude").Output()
	if err != nil {
		return
	}
	p := strings.TrimSpace(string(out))
	if p == "" {
		return
	}
	if !filepath.IsAbs(p) {
		p = filepath.Join(dir, p)
	}
	existing, _ := os.ReadFile(p)
	text := string(existing)
	var add strings.Builder
	if !strings.Contains(text, "saddle: per-agent grok") {
		if len(text) > 0 && !strings.HasSuffix(text, "\n") {
			add.WriteByte('\n')
		}
		add.WriteString("# saddle: per-agent grok hooks and mcp (local, do not commit)\n")
	}
	for _, pat := range patterns {
		if strings.Contains(text, pat) {
			continue
		}
		fmt.Fprintf(&add, "%s\n", pat)
	}
	if add.Len() == 0 {
		return
	}
	if err := os.MkdirAll(filepath.Dir(p), 0o755); err != nil {
		return
	}
	f, err := os.OpenFile(p, os.O_APPEND|os.O_CREATE|os.O_WRONLY, 0o644)
	if err != nil {
		return
	}
	defer f.Close()
	_, _ = f.WriteString(add.String())
}
