package agent

import (
	"encoding/json"
	"fmt"
	"io/fs"
	"os"
	"path/filepath"
	"strconv"
	"strings"
	"time"

	"github.com/brandonapol/saddle/internal/usage"
)

// advisory tells an agent saddle can't hook how to keep to its claims and finish.
const advisory = `
## Working without saddle hooks
Saddle can't watch this agent's writes, so your claims are advisory: nothing
stops a write to a file another task owns. Edit only files under your claims;
if you need anything else, say so in your done summary. Saddle notices are
typed into this session as lines starting with "[saddle]".
When you finish: commit everything, then run ` + "`saddle done -s \"<2-4 sentence summary>\"`" + `.
`

// hooklessPrompt is the first message for an agent with no system-prompt
// flag: the brief, the advisory rules, then the task prompt.
func hooklessPrompt(l Launch) string {
	return strings.TrimRight(l.Brief, "\n") + "\n" + advisory + "\n" + l.Prompt
}

// writeHookless writes the run dir for an agent without saddle hooks and a
// launch.sh that runs the shell line argv in the task's directory.
func (l Launch) writeHookless(name string, argv []string) (string, error) {
	if err := l.record(name); err != nil {
		return "", err
	}
	for file, body := range map[string]string{"brief.md": l.Brief, "prompt.md": hooklessPrompt(l)} {
		if err := os.WriteFile(filepath.Join(l.RunDir, file), []byte(body), 0o644); err != nil {
			return "", err
		}
	}
	env := l.env()
	var sh strings.Builder
	sh.WriteString("#!/usr/bin/env bash\n# Generated by saddle. Re-run to restart this agent.\n")
	for _, k := range []string{"SADDLE_ROOT", "SADDLE_TASK"} {
		fmt.Fprintf(&sh, "export %s=%s\n", k, shellQuote(env[k]))
	}
	fmt.Fprintf(&sh, "export PATH=%s:\"$PATH\"\n", shellQuote(filepath.Dir(l.Bin)))
	fmt.Fprintf(&sh, "cd %s || exit 1\n", shellQuote(l.Dir))
	fmt.Fprintf(&sh, "run=%s\n", shellQuote(l.RunDir))
	sh.WriteString(strings.Join(argv, " ") + "\n")
	fmt.Fprintf(&sh, "%s exited %s >/dev/null 2>&1\n", shellQuote(l.Bin), shellQuote(l.Task))
	sh.WriteString("echo; echo \"[saddle] agent exited. Re-run: bash $run/launch.sh\"; exec \"${SHELL:-bash}\"\n")
	launch := filepath.Join(l.RunDir, "launch.sh")
	if err := os.WriteFile(launch, []byte(sh.String()), 0o755); err != nil {
		return "", err
	}
	return "bash " + shellQuote(launch), nil
}

func (l Launch) cmdOr(def string) string {
	if l.Cmd != "" {
		return l.Cmd
	}
	return def
}

func quoteAll(args []string) []string {
	out := make([]string, len(args))
	for i, a := range args {
		out[i] = shellQuote(a)
	}
	return out
}

// hooklessInject types notices in whole, on one line: a newline would submit
// the message early.
func hooklessInject(notices string) string {
	var parts []string
	for _, line := range strings.Split(notices, "\n") {
		if line = strings.TrimSpace(line); line != "" {
			parts = append(parts, line)
		}
	}
	return "[saddle] " + strings.Join(parts, " | ")
}

// Codex is the OpenAI Codex CLI adapter: an interactive session with the
// saddle MCP server configured through -c overrides. Codex has no hooks, so
// claims are advisory and notices are typed in.
type Codex struct {
	// Home is Codex's state dir. Empty means $CODEX_HOME, then ~/.codex.
	Home string
}

func (Codex) Name() string                 { return usage.Codex }
func (Codex) Hooks() bool                  { return false }
func (Codex) Inject(notices string) string { return hooklessInject(notices) }

func (Codex) Launch(l Launch) (string, error) {
	env := l.env()
	argv := []string{shellQuote(l.cmdOr("codex"))}
	if l.Model != "" {
		argv = append(argv, "--model", shellQuote(l.Model))
	}
	argv = append(argv,
		"-c", shellQuote("mcp_servers.saddle.command="+strconv.Quote(l.Bin)),
		"-c", shellQuote(`mcp_servers.saddle.args=["mcp"]`),
		"-c", shellQuote(fmt.Sprintf("mcp_servers.saddle.env={SADDLE_ROOT=%s,SADDLE_TASK=%s}",
			strconv.Quote(env["SADDLE_ROOT"]), strconv.Quote(env["SADDLE_TASK"]))))
	argv = append(argv, quoteAll(l.Args)...)
	argv = append(argv, `"$(cat "$run/prompt.md")"`)
	return l.writeHookless(usage.Codex, argv)
}

func (c Codex) Usage() UsageSource {
	return UsageSource{Agent: usage.Codex, Transcript: c.transcript}
}

// transcript is the newest rollout whose session started in dir.
func (c Codex) transcript(dir, _, _ string) string {
	home := c.Home
	if home == "" {
		home = os.Getenv("CODEX_HOME")
	}
	if home == "" {
		h, _ := os.UserHomeDir()
		home = filepath.Join(h, ".codex")
	}
	var best string
	var bestMod time.Time
	_ = filepath.WalkDir(filepath.Join(home, "sessions"), func(p string, d fs.DirEntry, err error) error {
		if err != nil || d.IsDir() || !strings.HasPrefix(d.Name(), "rollout-") || !strings.HasSuffix(d.Name(), ".jsonl") {
			return nil
		}
		info, err := d.Info()
		if err != nil || !info.ModTime().After(bestMod) || rolloutCwd(p) != filepath.Clean(dir) {
			return nil
		}
		best, bestMod = p, info.ModTime()
		return nil
	})
	return best
}

// rolloutCwd reads the working directory from a rollout's session_meta line.
func rolloutCwd(path string) string {
	f, err := os.Open(path)
	if err != nil {
		return ""
	}
	defer f.Close()
	buf := make([]byte, 64<<10)
	n, _ := f.Read(buf)
	first, _, _ := strings.Cut(string(buf[:n]), "\n")
	var meta struct {
		Type    string `json:"type"`
		Payload struct {
			Cwd string `json:"cwd"`
		} `json:"payload"`
	}
	if json.Unmarshal([]byte(first), &meta) != nil || meta.Type != "session_meta" || meta.Payload.Cwd == "" {
		return ""
	}
	return filepath.Clean(meta.Payload.Cwd)
}

// Grok is the Grok CLI adapter, for one-shot work such as image generation:
// it runs headless with the prompt and tees its output to the run dir, where
// usage is read best effort. Grok gets no saddle hooks or MCP server, so
// claims are advisory and it finishes with the saddle CLI.
type Grok struct{}

func (Grok) Name() string                 { return usage.Grok }
func (Grok) Hooks() bool                  { return false }
func (Grok) Inject(notices string) string { return hooklessInject(notices) }

// grokTranscript is the tee'd output in the run dir.
const grokTranscript = "transcript.jsonl"

func (Grok) Launch(l Launch) (string, error) {
	if l.Kind == KindGrok {
		return l.writeGrok()
	}
	argv := []string{shellQuote(l.cmdOr("grok")), "--directory", shellQuote(l.Dir)}
	if l.Model != "" {
		argv = append(argv, "--model", shellQuote(l.Model))
	}
	argv = append(argv, quoteAll(l.Args)...)
	argv = append(argv, `--prompt "$(cat "$run/prompt.md")"`, "2>&1", "|", `tee -a "$run/`+grokTranscript+`"`)
	return l.writeHookless(usage.Grok, argv)
}

func (Grok) Usage() UsageSource {
	return UsageSource{Agent: usage.Grok, Transcript: func(_, runDir, _ string) string {
		return filepath.Join(runDir, grokTranscript)
	}}
}

// GrokWithHooks is a grok worker started with harness = "grok": project hooks
// and the saddle MCP server are installed, so claims are enforced.
type GrokWithHooks struct{}

func (GrokWithHooks) Name() string         { return usage.Grok }
func (GrokWithHooks) Hooks() bool          { return true }
func (GrokWithHooks) Inject(string) string { return WakeLine }
func (GrokWithHooks) Launch(l Launch) (string, error) {
	l.Kind = KindGrok
	return l.writeGrok()
}
func (GrokWithHooks) Usage() UsageSource { return Grok{}.Usage() }
